/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-contrib/registry/pkg/apis/sources/v1alpha1"
)

// FakeRegistrySources implements RegistrySourceInterface
type FakeRegistrySources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var registrysourcesResource = schema.GroupVersionResource{Group: "sources.knative.dev", Version: "v1alpha1", Resource: "registrysources"}

var registrysourcesKind = schema.GroupVersionKind{Group: "sources.knative.dev", Version: "v1alpha1", Kind: "RegistrySource"}

// Get takes name of the registrySource, and returns the corresponding registrySource object, and an error if there is any.
func (c *FakeRegistrySources) Get(name string, options v1.GetOptions) (result *v1alpha1.RegistrySource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(registrysourcesResource, c.ns, name), &v1alpha1.RegistrySource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistrySource), err
}

// List takes label and field selectors, and returns the list of RegistrySources that match those selectors.
func (c *FakeRegistrySources) List(opts v1.ListOptions) (result *v1alpha1.RegistrySourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(registrysourcesResource, registrysourcesKind, c.ns, opts), &v1alpha1.RegistrySourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RegistrySourceList{ListMeta: obj.(*v1alpha1.RegistrySourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.RegistrySourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested registrySources.
func (c *FakeRegistrySources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(registrysourcesResource, c.ns, opts))

}

// Create takes the representation of a registrySource and creates it.  Returns the server's representation of the registrySource, and an error, if there is any.
func (c *FakeRegistrySources) Create(registrySource *v1alpha1.RegistrySource) (result *v1alpha1.RegistrySource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(registrysourcesResource, c.ns, registrySource), &v1alpha1.RegistrySource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistrySource), err
}

// Update takes the representation of a registrySource and updates it. Returns the server's representation of the registrySource, and an error, if there is any.
func (c *FakeRegistrySources) Update(registrySource *v1alpha1.RegistrySource) (result *v1alpha1.RegistrySource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(registrysourcesResource, c.ns, registrySource), &v1alpha1.RegistrySource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistrySource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRegistrySources) UpdateStatus(registrySource *v1alpha1.RegistrySource) (*v1alpha1.RegistrySource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(registrysourcesResource, "status", c.ns, registrySource), &v1alpha1.RegistrySource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistrySource), err
}

// Delete takes name of the registrySource and deletes it. Returns an error if one occurs.
func (c *FakeRegistrySources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(registrysourcesResource, c.ns, name), &v1alpha1.RegistrySource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRegistrySources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(registrysourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RegistrySourceList{})
	return err
}

// Patch applies the patch and returns the patched registrySource.
func (c *FakeRegistrySources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RegistrySource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(registrysourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RegistrySource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistrySource), err
}
