/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-contrib/registry/pkg/apis/bindings/v1alpha1"
)

// FakeRegistryBindings implements RegistryBindingInterface
type FakeRegistryBindings struct {
	Fake *FakeBindingsV1alpha1
	ns   string
}

var registrybindingsResource = schema.GroupVersionResource{Group: "bindings.knative.dev", Version: "v1alpha1", Resource: "registrybindings"}

var registrybindingsKind = schema.GroupVersionKind{Group: "bindings.knative.dev", Version: "v1alpha1", Kind: "RegistryBinding"}

// Get takes name of the registryBinding, and returns the corresponding registryBinding object, and an error if there is any.
func (c *FakeRegistryBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.RegistryBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(registrybindingsResource, c.ns, name), &v1alpha1.RegistryBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistryBinding), err
}

// List takes label and field selectors, and returns the list of RegistryBindings that match those selectors.
func (c *FakeRegistryBindings) List(opts v1.ListOptions) (result *v1alpha1.RegistryBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(registrybindingsResource, registrybindingsKind, c.ns, opts), &v1alpha1.RegistryBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RegistryBindingList{ListMeta: obj.(*v1alpha1.RegistryBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.RegistryBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested registryBindings.
func (c *FakeRegistryBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(registrybindingsResource, c.ns, opts))

}

// Create takes the representation of a registryBinding and creates it.  Returns the server's representation of the registryBinding, and an error, if there is any.
func (c *FakeRegistryBindings) Create(registryBinding *v1alpha1.RegistryBinding) (result *v1alpha1.RegistryBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(registrybindingsResource, c.ns, registryBinding), &v1alpha1.RegistryBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistryBinding), err
}

// Update takes the representation of a registryBinding and updates it. Returns the server's representation of the registryBinding, and an error, if there is any.
func (c *FakeRegistryBindings) Update(registryBinding *v1alpha1.RegistryBinding) (result *v1alpha1.RegistryBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(registrybindingsResource, c.ns, registryBinding), &v1alpha1.RegistryBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistryBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRegistryBindings) UpdateStatus(registryBinding *v1alpha1.RegistryBinding) (*v1alpha1.RegistryBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(registrybindingsResource, "status", c.ns, registryBinding), &v1alpha1.RegistryBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistryBinding), err
}

// Delete takes name of the registryBinding and deletes it. Returns an error if one occurs.
func (c *FakeRegistryBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(registrybindingsResource, c.ns, name), &v1alpha1.RegistryBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRegistryBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(registrybindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RegistryBindingList{})
	return err
}

// Patch applies the patch and returns the patched registryBinding.
func (c *FakeRegistryBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RegistryBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(registrybindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RegistryBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegistryBinding), err
}
