/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing-contrib/registry/pkg/apis/sources/v1alpha1"
	scheme "knative.dev/eventing-contrib/registry/pkg/client/clientset/versioned/scheme"
)

// RegistrySourcesGetter has a method to return a RegistrySourceInterface.
// A group's client should implement this interface.
type RegistrySourcesGetter interface {
	RegistrySources(namespace string) RegistrySourceInterface
}

// RegistrySourceInterface has methods to work with RegistrySource resources.
type RegistrySourceInterface interface {
	Create(*v1alpha1.RegistrySource) (*v1alpha1.RegistrySource, error)
	Update(*v1alpha1.RegistrySource) (*v1alpha1.RegistrySource, error)
	UpdateStatus(*v1alpha1.RegistrySource) (*v1alpha1.RegistrySource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RegistrySource, error)
	List(opts v1.ListOptions) (*v1alpha1.RegistrySourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RegistrySource, err error)
	RegistrySourceExpansion
}

// registrySources implements RegistrySourceInterface
type registrySources struct {
	client rest.Interface
	ns     string
}

// newRegistrySources returns a RegistrySources
func newRegistrySources(c *SourcesV1alpha1Client, namespace string) *registrySources {
	return &registrySources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the registrySource, and returns the corresponding registrySource object, and an error if there is any.
func (c *registrySources) Get(name string, options v1.GetOptions) (result *v1alpha1.RegistrySource, err error) {
	result = &v1alpha1.RegistrySource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("registrysources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RegistrySources that match those selectors.
func (c *registrySources) List(opts v1.ListOptions) (result *v1alpha1.RegistrySourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RegistrySourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("registrysources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested registrySources.
func (c *registrySources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("registrysources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a registrySource and creates it.  Returns the server's representation of the registrySource, and an error, if there is any.
func (c *registrySources) Create(registrySource *v1alpha1.RegistrySource) (result *v1alpha1.RegistrySource, err error) {
	result = &v1alpha1.RegistrySource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("registrysources").
		Body(registrySource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a registrySource and updates it. Returns the server's representation of the registrySource, and an error, if there is any.
func (c *registrySources) Update(registrySource *v1alpha1.RegistrySource) (result *v1alpha1.RegistrySource, err error) {
	result = &v1alpha1.RegistrySource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("registrysources").
		Name(registrySource.Name).
		Body(registrySource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *registrySources) UpdateStatus(registrySource *v1alpha1.RegistrySource) (result *v1alpha1.RegistrySource, err error) {
	result = &v1alpha1.RegistrySource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("registrysources").
		Name(registrySource.Name).
		SubResource("status").
		Body(registrySource).
		Do().
		Into(result)
	return
}

// Delete takes name of the registrySource and deletes it. Returns an error if one occurs.
func (c *registrySources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("registrysources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *registrySources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("registrysources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched registrySource.
func (c *registrySources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RegistrySource, err error) {
	result = &v1alpha1.RegistrySource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("registrysources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
